### ISSUE TITLE
عدم نمایش تصویر بعد از آپلود

### ISSUE THREAD

**Issue by Hamidnch** [rabbal/MVC5#1]
سلام.
یه مشکل تو آپلود تصویر داخل فولدرها در بخش مدیریت وجود داره که بعد از آپلود تصاویر دیده  نمیشوند.
همچنین توی اسلاید شو صفحه اول هم عکس نشون داده نمیشه.

**Comment by rabbal** [comment]
همچین قسمتی اصلا در این پروژه وجود ندارد!

**Comment by Hamidnch** [comment]
درسته.من منظورم پروژه 
GoldenCityShop
شما بود.به اشتباه اینجا یادداشت گذاشتم!
